//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetDesigner.rc
//
#define ID_SPECIAL                      2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_TOOLBOX_WND                 156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_POPUP_EDIT2                 201
#define ID_VIEW_TOOLBARWND              202
#define IDR_POPUP_EDIT3                 202
#define IDR_POPUP_EDIT4                 203
#define IDR_POPUP_EDIT5                 204
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_VIEW_APPLOOK_LIGHT           220
#define ID_VIEW_APPLOOK_DARK            221
#define ID_VIEW_APPLOOK_COLORS          222
#define IDR_POPUP_GRAPH                 223
#define IDR_POPUP_EDIT6                 224
#define IDR_POPUP_EDIT7                 225
#define IDR_POPUP_EDIT8                 226
#define IDR_POPUP_EDIT9                 227
#define IDR_POPUP_EDIT10                228
#define IDR_POPUP_EDIT11                229
#define IDS_TRAIN_TAB                   300
#define IDS_ERRORS_TAB                  301
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_TOOLBOX_BUTTONS             312
#define IDD_GUIDESETTINGS               317
#define IDC_POINTER                     321
#define IDC_NODE                        323
#define IDD_SETTINGS                    324
#define IDB_WRITE16                     327
#define IDB_WRITE32                     328
#define IDB_BUTTONS32                   329
#define IDB_BUTTONS16                   330
#define IDB_CLASSVIEW16                 333
#define IDI_FILE_VIEW1                  338
#define IDI_TOOLBOX_VIEW                339
#define IDI_TOOLBOX_VIEW1               340
#define IDI_TOOLBOX_VIEW_HC             340
#define IDI_GRAPH_VIEW                  341
#define IDI_TOOLBOX_VIEW_HC1            342
#define IDI_GRAPH_VIEW_HC               342
#define IDD_MATH                        348
#define IDD_NORMALIZE                   350
#define IDD_DATE_TIME                   352
#define IDD_FFT                         354
#define IDD_DERIVATIVE                  356
#define IDD_COPYRIGHT_OPTIONS           361
#define IDD_DEFAULT_OPTIONS             362
#define ID_VIEW_GRAPHWND                363
#define IDD_NORM_SCALE                  363
#define IDD_OUTPUT_VIEW                 364
#define ID_VIEW_CLUSTERGRAPHWND         365
#define IDD_ACTIVATION                  366
#define IDD_DATA_SETS                   368
#define IDB_FILEOPEN                    374
#define IDD_RANDOM_SEED                 376
#define IDD_AUTONET                     378
#define IDD_STATUS                      384
#define IDD_AUTORNN                     386
#define IDD_EVALUATE_DLG                388
#define IDD_AUTOENCODER                 390
#define IDD_GRAPH_OPTIONS               392
#define IDD_IMAGE_VIEW                  394
#define ID_VIEW_INPUT_DATAWND           395
#define IDD_DATE_TIME1                  395
#define IDD_IMAGE_NAME_PARSER           395
#define IDD_INFO                        396
#define IDD_STATUS1                     397
#define IDD_STATUS2                     397
#define IDD_DIALOG1                     398
#define IDD_EXPORT                      398
#define IDD_INITIALIZATION1             400
#define IDD_INITIALIZATION2             401
#define ID_VIEW_PROCESSWND              402
#define IDD_NORMALIZE1                  402
#define IDD_DICTIONARY_PROCESS          402
#define IDD_FIELD_KEY                   404
#define IDD_OUTPUT_VIEW1                405
#define IDD_EVALUATE_FILE               405
#define IDD_FFT1                        406
#define IDD_CLUSTER_DLG                 406
#define IDD_FILE_TYPE                   408
#define IDD_SAVE_DATA_OPTIONS           410
#define IDD_LAYER_DATA                  412
#define IDD_INITIALIZATION3             413
#define IDD_SAVE_WEIGHTS_DLG            414
#define IDD_AUTOMATION_DLG              416
#define IDD_INPUT_OPTIMIZATION          418
#define IDR_POPUP_CLUSTER_GRAPH         419
#define IDD_ASSEMBLY_PICKER_DLG         420
#define IDC_SCROLLBAR1                  1000
#define IDC_LIST2                       1003
#define IDC_LIST1                       1004
#define IDC_LIST3                       1004
#define IDC_LINEAR                      1008
#define IDC_NO_VALIDATION               1008
#define IDC_LINEAR2                     1009
#define IDC_LOGARITHMIC                 1009
#define IDC_RANDOMIZED                  1009
#define IDC_SPACING                     1010
#define IDC_FROM_FILE                   1010
#define IDC_LOGARITHMIC2                1010
#define IDC_THIRD                       1010
#define IDC_SPACING2                    1011
#define IDC_LOGARITHMIC3                1011
#define IDC_FOURTH                      1011
#define IDC_CLEAR                       1014
#define IDC_SELECT_FILE                 1014
#define IDC_RESET_FACTORS               1014
#define IDC_FILE_OPEN                   1014
#define IDC_INPUTS                      1014
#define IDC_TAB1                        1015
#define IDC_NORM_OPTIONS                1015
#define IDC_OUTPUTS                     1015
#define IDC_LOWER_NORM_FACTOR           1016
#define IDC_UPPER_NORM_FACTER           1017
#define IDC_DISSALLOW                   1018
#define IDC_VALIDATION_SET              1018
#define IDC_INPUT_NODES                 1018
#define IDC_LOWER_NORM_FACTOR2          1018
#define IDC_RESET                       1019
#define IDC_OUTPUT_NODE2                1019
#define IDC_UPPER_NORM_FACTER2          1019
#define IDC_SAVE_OPTIONS                1020
#define IDC_COMBO1                      1021
#define IDC_ETA                         1022
#define IDC_ALPHA                       1023
#define IDC_LOWER                       1023
#define IDC_RAND                        1024
#define IDC_UPPER                       1024
#define IDC_SLEAK                       1025
#define IDC_RLEAK                       1026
#define IDC_SAVE_CSV                    1026
#define IDC_SLEAK2                      1026
#define IDC_SLIDER1                     1027
#define IDC_SAVE_CSV2                   1027
#define IDC_SHOW_ALL                    1027
#define IDC_RLEAK2                      1027
#define IDC_MIN_SOUND_LEVEL             1027
#define IDC_BIASHIGH                    1028
#define IDC_RLEAK3                      1028
#define IDC_PPROCESSING                 1028
#define IDC_BIAS_TEXT                   1031
#define IDC_FILTER                      1031
#define IDC_BACK_FRAME                  1032
#define IDC_EDIT1                       1033
#define IDC_VALIDATION_FILENAME         1034
#define IDC_HEIGHT                      1034
#define IDC_MFCEDITBROWSE1              1035
#define IDC_MFCVSLISTBOX1               1036
#define IDC_NUM_INPUTS                  1037
#define IDC_HIDDEN_NODES                1038
#define IDC_NUM_LAYERS                  1039
#define IDC_HIDDEN_WIDTH                1040
#define IDC_NUM_OUTPUTS                 1041
#define IDC_INPUT_LABEL1                1042
#define IDC_INPUT_LABEL2                1043
#define IDC_HIDDEN_LABEL2               1044
#define IDC_HIDDEN_LABEL3               1045
#define IDC_HIDDEN_LABEL1               1046
#define IDC_OUTPUT_LABEL1               1047
#define IDC_OUTPUT_LABEL2               1048
#define IDC_NORMALIZE                   1049
#define IDC_PROGRESS1                   1055
#define IDC_SECONDS                     1056
#define IDC_MINUTES                     1057
#define IDC_HOURS                       1058
#define IDC_DAYS                        1059
#define IDC_DATETIMEPICKER1             1060
#define IDC_FILL_WITH_VALUE             1065
#define IDC_LABEL1                      1069
#define IDC_LABEL2                      1070
#define IDC_SECOND                      1071
#define IDC_LABEL3                      1071
#define IDC_RELATIVE                    1072
#define IDC_GREY_SCALE                  1072
#define IDC_LABEL                       1073
#define IDC_EVALUATE                    1074
#define IDC_OUTLINE                     1075
#define IDC_VERT_LINE                   1076
#define IDC_UPDATE                      1077
#define IDC_STATIC1                     1078
#define IDC_HORZ1                       1079
#define IDC_STATIC4                     1079
#define IDC_VERT2                       1080
#define IDC_HORZ2                       1080
#define IDC_YMIN                        1080
#define IDC_STATIC5                     1080
#define IDC_YMIN_BUTTON                 1081
#define IDC_YMAX                        1082
#define IDC_NOTES                       1082
#define IDC_YMIN_BUTTON2                1083
#define IDC_YMAX_BUTTON                 1083
#define IDC_NOTES2                      1083
#define IDC_MIMAGE                      1084
#define IDC_NOTES3                      1085
#define IDC_WIDTH                       1086
#define IDC_GRAY_TEXT                   1087
#define IDC_SELECT_FILES                1089
#define IDC_NAME1                       1089
#define IDC_FILE_COMBO                  1090
#define IDC_NAME2                       1090
#define IDC_FILE_DATA                   1091
#define IDC_NAME3                       1091
#define IDC_LINE1                       1092
#define IDC_CHECK1                      1093
#define IDC_SUB_CHECK                   1093
#define IDC_CONV1_OPTION                1094
#define IDC_SERIES_DATA2                1094
#define IDC_CONV2_OPTION                1095
#define IDC_SELECT_FILE2                1095
#define IDC_CONV3_OPTION                1096
#define IDC_RADIO1                      1096
#define IDC_RADIO2                      1097
#define IDC_RADIO3                      1098
#define IDC_CONTINUE                    1098
#define IDC_SAVED_WEIGHTS               1099
#define IDC_RANDOMIZE                   1100
#define IDC_BUTTON1                     1101
#define IDC_STATUS_CANCEL               1101
#define IDC_EVALUATE_FILE               1101
#define IDC_LOAD_DATA                   1101
#define IDC_TEXT                        1102
#define IDC_NORM_RADIO                  1102
#define IDC_BUTTON3                     1102
#define IDC_REMOVE                      1102
#define IDC_ONE_RADIO                   1103
#define IDC__HUFF_RADIO                 1104
#define IDC_HUFF_RADIO                  1104
#define IDC_NUM_RADIO                   1105
#define IDC_LINE2                       1106
#define IDC_STATIC_BOX                  1107
#define IDC_NUM_RADIO2                  1108
#define IDC_ONR_SHOT_RADIO              1108
#define IDC_GARDEN                      1109
#define IDC_NUM_CLUSTERS                1109
#define IDC_O                           1109
#define IDC_DICTIONARY_RADIO            1109
#define IDC_BLUE                        1110
#define IDC_STATIC2                     1110
#define IDC_LIGHT4                      1111
#define IDC_STATIC3                     1111
#define IDC_BUTTON2                     1112
#define IDC_SAVE                        1112
#define IDC_SELECT_FOLDER               1113
#define IDC_NORMALIZE_FILE_SET          1113
#define IDC_NORMALIZE_FILES             1113
#define IDC_NORMALIZE_PER_FILE          1114
#define IDC_CLASSIFICATION_MATRICES     1115
#define IDC_NET_OUTPUT_DATA             1116
#define IDC_COMPACT                     1116
#define IDC_TRAIN_OUTPUT_DATA           1117
#define IDC_ADD                         1117
#define IDC_TRAIN_INPUT_DATA            1118
#define IDC_VALIDATION_RESPONSE         1118
#define IDC_TRAIN_RESPONSE              1119
#define IDC_SAVE_DELAY_EPOCHS           1120
#define IDC_SAVE_WEIGHTS                1121
#define IDC_RESTORE_WEIGHTS             1122
#define IDC_SAVE_DELAY_EPOCHS2          1123
#define IDC_EVALUATE_INPUTS             1123
#define IDC_                            1124
#define IDC_OPTIMIZE_TRAIN              1125
#define IDC_OPTIMIZE_VALIDATION         1126
#define IDC_CARTOON                     1127
#define IDC_NEW_ASSEMBLY                1128
#define IDC_EXISTING_ASSEMBLY           1129
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_TOOLS_PANEL                  32771
#define ID_OUTPUT_PANEL                 32772
#define ID_CLASS_VIEW                   32773
#define ID_ZOOM_FIT                     32774
#define ID_NODE_VIEW                    32775
#define ID_ATTENTION                    32776
#define ID_GUIDE_SETTINGS               32778
#define ID_OFFICE2007_DARKTHEME         32781
#define ID_SLIDER2                      32783
#define ID_SNAP                         32784
#define ID_GRID                         32787
#define ID_100_PERCENT                  32789
#define ID_ZOOM_SELECTION               32790
#define ID_STOP_TRAIN                   32793
#define ID_UNDO                         32794
#define ID_REDO                         32795
#define ID_TRAIN_BUTTON                 32796
#define ID_SELECT_ALL                   32797
#define ID_SELECT_CONNECTS              32798
#define ID_SELECT_OTHER                 32799
#define ID_SELECT_NODES                 32800
#define ID_CHECK2                       32801
#define ID_REDRAW                       32802
#define ID_EDIT_MOVE                    32803
#define ID_VIEW_APPLOOK_COLORFUL        32804
#define ID_OPTIONS                      32805
#define ID_ZOOM_OUT                     32806
#define ID_HIDDEN                       32807
#define ID_OUTPUT                       32808
#define ID_CONNECT                      32809
#define ID_DATA_INPUT                   32810
#define ID_DATA_OUTPUT                  32811
#define ID_CSV_DATA                     32812
#define ID_BUFFER                       32813
#define ID_VERIFY_NET                   32814
#define ID_VIEW_DATA                    32817
#define ID_VALIDATION_SET               32818
#define ID_EQUATION                     32819
#define ID_ARROWS                       32820
#define ID_EPOCHS                       32821
#define ID_TIME_HRS                     32822
#define ID_ERROR_RATE                   32823
#define ID_DELTA_ERROR                  32824
#define ID_GRAPH_TRAIN_ERROR            32825
#define ID_GRAPH_OUTPUTS                32826
#define ID_MIN_EPOCHS                   32828
#define ID_EDIT3                        32829
#define ID_RANDOMIZE                    32830
#define ID_L1NORM                       32831
#define ID_UPDATE_RATE                  32832
#define ID_TRAIN_DATA                   32833
#define ID_NET_DIAG                     32834
#define ID_SHOW_WEIGHTS                 32835
#define ID_WEIGHT_COMPRESS              32836
#define ID_OUTPUT_DATA                  32837
#define ID_L2NORM                       32838
#define ID_AUTOROUTE                    32839
#define ID_KMEANS                       32840
#define PCA                             32841
#define ID_RANDOM_SEED                  32842
#define ID_TRAIN_ENABLED                32843
#define ID_NODE_ANALYSIS                32844
#define ID_PROPCTRL_CLASS               32845
#define ID_TEST                         32845
#define ID_GRAPH_DATA                   32846
#define ID_SAVE_CSV                     32846
#define ID_GRAPH_SCALE                  32847
#define ID_CONV_LAYER                   32847
#define ID_SHOW_CONNECTS                32848
#define ID_AUTOSAVE                     32849
#define ID_INFO                         32850
#define ID_CLEAR                        32851
#define ID_BUTTON5                      32854
#define ID_BUTTON2                      32855
#define ID_EVALUATE_FILE                32856
#define ID_BUTTON3                      32857
#define ID_BUTTON4                      32858
#define ID_SELECT_DATA                  32859
#define ID_SELF_ATTENTION               32860
#define ID_ZERO_OUTPUT                  32861
#define ID_AUTOMATION                   32862
#define ID_BUTTON9                      32863
#define ID_NET_CLUSTER                  32863
#define ID_CLUSTER                      32864
#define ID_SAVE_CLUSTER                 32865
#define ID_CLUSTER_GRAPH                32866
#define ID_SELECT_DECODER               32867
#define ID_DROPOUT                      32868
#define ID_ATTENTION2                   32869
#define ID_ASSEMBLY                     32870
#define ID_EDIT_ASSEMBLY                32871
#define ID_CLOSE_ASSEMBLY               32872
#define ID_ASSY_LAYER                   32874

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        422
#define _APS_NEXT_COMMAND_VALUE         32875
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
